spring:
  application:
    name: app-microservice-location-consumer
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/landscapedb
    username: landscape
    password: landscape
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: landscapes

app:
  rabbitmq:
    exchange: landscape.exchange
    queue: landscape.pending.queue
    routing-key: landscape.pending

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  chat-id: ${TELEGRAM_CHAT_ID:}