spring:
  application:
    name: app-microservice-location-consumer
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /

server:
  port: 8002

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  rabbitmq:
    exchange: landscape.exchange
    queue: landscape.pending.queue
    routing-key: landscape.pending
    status-queue: landscape.status.queue
    status-routing-key: landscape.status

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  chat-id: ${TELEGRAM_CHAT_ID:}